config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @completed = completed(@task)
  end

  def completed(task)
   if task.completed == true
    "The task is completed"
   else
    "This task is not completed yet!"
   end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # no need for app/views/restaurants/create.html.erb
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end

  private
  
  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="titulo text-center" >Edit task!</h1>
  <div class="form-group">
      <%= form_for(@task) do |f| %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= f.label :title %>
        <%= f.text_field :title,class:"form-control" %>
        <%= f.label :details %>
        <%= f.text_area :details,class:"form-control mb-4" %>
        <%= f.submit class:"btn btn-dark"  %>
      <% end %>
      <%= link_to "GO BACK", tasks_path, class:"btn btn-dark mt-3" %>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container text-center mt-4">
  <h1 class="titulo">My Tasks</h1>
  <ul>
  <% @tasks.each do |task|%>
  <li class = "listasinpunto">
  <%=task.completed == true ? "✔": "❌"%> <%= link_to "#{task[:title]}", task_path(task.id) %> <%= link_to " 🗑", delete_path(task), method: :delete %>
  </li >
  <% end %>
  </ul>
  <%= link_to "Add a new task", tasks_new_path, class: "btn btn-dark" %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="titulo text-center">New task!</h1>
  <div class="form-group">
    <%= form_for(@task) do |f| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= f.label :title %>
      <%= f.text_field :title,class:"form-control" %>
      <%= f.label :details %>
      <%= f.text_area :details,class:"form-control mb-4" %>
      <%= f.submit class:"btn btn-dark"  %>
    <% end %>
    <%= link_to "GO BACK", tasks_path, class:"btn btn-dark mt-3" %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container text-center">
  <h3 class="tarea text-center p-2"><%= @task.title %></h4>
  <h5><%= @task.details %></h5>
  <p><%= @completed %></p>
  <%= link_to "GO BACK", tasks_path, class: "btn btn-dark" %>
  <%= link_to "EDIT TASK", edit_path, class: "btn btn-dark" %>
</div>